xyz = 1,2,3,4,5,56,1.5

print(len(xyz)) # len() shows length of the iterable...

print(min(xyz)) # min() shows minimum of the iterable...

print(max(xyz)) # max() shows maximum of the iterable...

x = 22/7

print(round(x)) # round() rounds the number....
print(abs(x)) # abs() prints absolute value....


