my_list = [1,20,40]
print(my_list)

my_list_2 = [45,4.55,'a']
print(my_list_2)
my_list.extend(my_list_2)
print(my_list)
my_list.pop()
print(my_list)
my_list.insert(9,54)
print(my_list)
my_list.insert(1,54)
my_list.insert(6,54)
my_list.insert(10,54)
my_list.insert(3,234)
my_list.sort()

print(my_list)
my_list.pop()
print(my_list)
my_list.pop()
print(my_list)
my_list.pop()
print(my_list)
my_list.pop()
print(my_list)
my_list.pop()
print(my_list)
